### ISSUE TITLE
no `No Results for "[special characters]"` on stage

### ISSUE THREAD

**Issue by pkikawa** [denshoproject/encyc-rg#71]
searching for special characters on rg stage will either not display the `No Results for "[special characters]"` or throw a 500 error depending on the character. 

characters ~ [ ] / \ + { } : ! ^  will throw a 500 error

* returns 1489 results on stage. on prod it returns the standard `No Results for "[special characters]"`

**Comment by gjost** [comment]
FWIW after working on all this for awhile, I thought to check the DR.  It has the same problem, it's just covered over by a 500 error when you search on these terms.

**Comment by gjost** [comment]
Fixed in `encyc-rg` commit `27f7400` for package `encycrg-develop_3.0.0-rc2`.
