### ISSUE TITLE
Add IA DLJAI link to article page

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-rg#80]
Some articles have a corresponding item in IA's Digital Library of Japanese American Incarceration (DLJAI) collection.  In similar fashion to how the "For More Information" and "Footnotes" sections are handled, the "Find in the Digital Library of Japanese American Incarceration" section should appear in a styled accordion drop down. 

This will require edits to the `article.html` template and `models.py`.  It also relies on a custom template (`Template:FindAtIA`) in the editors' mediawiki.

**Comment by gjost** [comment]
Ah, I get it, there's a new section in the MediaWiki page analogous to the Footnotes and More Info sections.  Let me know when the template has been added to MW and I'll take a look and see what changes we need to make to the back-end.

**Comment by GeoffFroh** [comment]
Addressed in a6cf21d10012f97976034391fd82589baf037997
